apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  namespace: xyz-fin-ns
  labels:
    app: vote
  name: vote
spec:
  replicas: 20
  selector:
    matchLabels:
      app: vote
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: vote
    spec:
      containers:
      - image: etahmom/vote:v2
        name: vote
        resources: {}
status: {}
