apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  namespace: xyz-fin-ns
  labels:
    app: db
  name: db
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: db-service
  type: ClusterIP
status:
  loadBalancer: {}